name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  jekyll:
    runs-on: ubuntu-20.04 # You can change this to ubuntu-latest if you want, shouldn't break
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages